import os

SetOption('implicit_cache', 1)

# Object('Casting_type/static_cast_test.c', CPPPATH = './Libs')
# Object('memory_func/memmove_test.c', CPPPATH = './Libs')
# Object('multi-argument/multi_arg.c', CPPPATH = './Libs')
# Object('Struct/struct_test.c', CPPPATH = './Libs')
# Object('Union/union_test.c', CPPPATH = './Libs')

file_list = ['main.c',
            'Casting_type/static_cast_test.c',
            'memory_func/memmove_test.c',
            'multi-argument/multi_arg.c',
            'Struct/struct_test.c',
            'Union/union_test.c',
            'function_ptr/function_ptr.c']
folder_list = ['./Libs',
                './Casting_type',
                './memory_func',
                './multi-argument',
                './Struct',
                './Union',
                './function_ptr',
                '.']

Program(file_list, CPPPATH = folder_list)
Decider('MD5-timestamp')